clear
clc
syms Ixx Iyy Izz Ixz;
syms psi theta phi p q r;
syms x y z u v w;
syms m g;
syms Fx Fy Fz L M N;
I_b = [Ixx 0 -Ixz;...
        0 Iyy 0;...
        -Ixz 0 Izz]; % body frame moment of inertia. It does not vary with wing flapping.
R_x = [1 0 0;...
    0 cos(phi) -sin(phi);...
    0 sin(phi) cos(phi)];
R_y = [cos(theta) 0 sin(theta);...
        0 1 0;
        -sin(theta) 0 cos(theta)];
R_z = [cos(psi) -sin(psi) 0;...
    sin(psi) cos(psi) 0;...
    0 0 1];
g_e = [0;0;g];
R_b2e = R_z*R_y*R_x;
V_b = [u;v;w]; % body velocity in earth frame
% Need to ensure kinematics p, q and r are local body p,q and r not
% global roll, pitch and yaw rates.
X = [x;y;z;u;v;w;phi;theta;psi;p;q;r];
T = [1 sin(phi)*tan(theta) cos(phi)*tan(theta);...
    0 cos(phi) -sin(phi);...
    0 sin(phi)*sec(theta) cos(phi)*sec(theta)];
Omega_b = [0 -r q;...
          r 0 -p;...
         -q p 0]; % skew symm
Zero = zeros(3,3);
One = eye(3,3);
A_matrix = [Zero R_b2e Zero Zero; ...
            Zero -Omega_b Zero Zero;...
            Zero Zero Zero T;...
            Zero Zero Zero -I_b\Omega_b*I_b]; % state transition matrix
B_matrix = [Zero Zero Zero;...
    1/m*One Zero R_b2e\One;...
    Zero Zero Zero;...
    Zero I_b\One Zero];
U = [Fx;Fy;Fz;L;M;N;g_e];
X_dot = simplify(A_matrix*X + B_matrix*U)